config/routes.rb
Rails.application.routes.draw do

  # root page, welcome new users
  root "pages#welcome", as: "welcome"

  # static pages
  get 'pages/welcome'
  get 'pages/helper'


  # users
  resources :users
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/dashboard', to: 'users#dashboard'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  # containers
  resources :containers do
    collection do
      post 'switch'
    end
  end

  get 'qr', to: 'containers#qr'


end

app/views/dashboard/_cards.html.erb
<% @containers.each do |container| %>

    <div class="card container-card" id="card-<%= container.container_hash %>">
      <div class="card-header">
        <span>ID: <%= container.short_id %></span>

        <div class="switch pull-right">
          <input
          type="checkbox"
          id="<%= container.container_hash %>"

          data-id="<%= container.id %>"
          data-container_hash="<%= container.container_hash %>"
          />
          <label for="<%= container.container_hash %>"></label>
        </div>


      </div>
      <div class="card-body">
        <div class="row">

          <ul class="list-group list-group-flush col-12 col-md-8">
            <li class="list-group-item">
              <%= t("addr") %>:
              <code class="pull-right"><%= container.host %></code>
            </li>

            <li class="list-group-item">
              <%= t("port") %>:

              <code class="pull-right port">
                <% if container.running? %>
                    <%= container.port %>
                <% else %>
                    <%= fa_icon "question-circle" %>
                <% end %>
              </code>
            </li>

            <li class="list-group-item">
              <%= t("encryption") %>:
              <code class="pull-right"><%= container.encryption %></code>
            </li>

            <li class="list-group-item">
              <%= t("password") %>:
              <code class="pull-right"><%= container.password %></code>
            </li>
          </ul>

          <div class="qr col-8 offset-2 col-md-4 offset-md-0">
            <% if container.running? %>
                <img src="/qr?str=<%= container.qr_url %>">
            <% end %>
          </div>

        </div>
      </div>
    </div>

    <div class="w-100"></div>

    <% if container.running? %>
        <script>
            // default closed: none of checked
            $("input#<%= container.container_hash %>").addClass("checked");
        </script>
    <% end %>

<% end %>


<script>
    // container card switch
    $(".switch input").click(function () {
        var container_hash = $(this).data("container_hash");
        var id = $(this).data("id");
        console.debug("container_hash", container_hash);
        console.debug("id", id);

        if ($(this).hasClass("disabled")) {
            console.debug("switch input is disabled.");
            return false;
        }

        var ajax_options = {
            type: "POST",
            async: true,
            url: "/containers/switch.js",
            data: {
                "container_hash": container_hash,
                "id": id
            },
            dataType: "script",
        };


        if ($(this).hasClass("checked")) {
            console.debug("turn off");
            $(this).removeClass("checked");//switch btn
            $("#card-" + container_hash + " code.port").html("<%= j fa_icon "question-circle" %>");// port => ?
            $("#card-" + container_hash + " div.qr").empty();// empty qr img
            ajax_options['data']['turn'] = 'off';

        } else {
            console.debug("turn on");
            $(this).addClass("checked");//switch btn
            ajax_options['data']['turn'] = 'on';
        }

        console.debug('ajax_options', ajax_options);
        $.ajax(ajax_options);

        // avoid double click switch btn
        // remove disable when callback
        $(this).addClass("disabled");
    });
</script>

app/views/dashboard/_header.html.erb
<div class="header fixed-top">
  <div class="container">

    <nav class="navbar navbar-expand-sm ">

      <%= link_to "Secretube", dashboard_url, class: "logo-text" %>

      <button class="navbar-toggler" id="sm_screen_toggle_btn"
              type="button"
              data-toggle="collapse" data-target="#navbar_collapse">
        <span class="navbar-toggler-icon"></span></button>

      <div class="navbar-collapse collapse" id="navbar_collapse">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="#">History</a>
          </li>
        </ul>

        <ul class="navbar-nav ">
          <li class="nav-item">
            <%= link_to t("help_page"), pages_helper_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to t("logout"), logout_path, method: :delete, class: "nav-link" %>
          </li>
        </ul>
      </div>


    </nav>
  </div>
</div>

app/views/dashboard/main.html.erb
<div class="container">
  <div class="row">
    <div class="col-10 offset-1 col-md-5">
      <%= button_to containers_path,
                    method: :post,
                    class: "btn btn-block btn-outline-primary",
                    remote: true,
                    format: :js,
                    id: "create_tube" do %>
          <%= fa_icon "plus" %>
          <%= t("create_tube") %>
      <% end %>
    </div>
  </div>


  <div class="row">
    <div id="container_cards" class="col-10 offset-1"><%= render "dashboard/cards" %></div>
  </div>
</div>



<script>
    $(function () {
        $("#create_tube").click(function () {
            $("#create_tube .fa-plus").addClass("fa-pulse");
            $(this).addClass("disabled"); //with CSS: pointer-events: none;
        });
    });
</script>