config/routes.rb
Rails.application.routes.draw do

  # root page, welcome new users
  root "pages#welcome", as: "welcome"

  # static pages
  get 'pages/welcome'
  get 'pages/helper'


  # users
  resources :users
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/dashboard', to: 'users#dashboard'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  # containers
  resources :containers do
    collection do
      post 'switch'
    end
  end

  get 'qr', to: 'containers#qr'


end

app/views/pages/helper.html.erb
<div id="helper_page">

</div>

app/views/pages/welcome.html.erb
<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta charset="UTF-8">
  <title>Secretube</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <%= stylesheet_link_tag 'welcome', media: 'all' %>
  <%= favicon_link_tag("logo.png") %>
  <%= javascript_include_tag 'welcome' %>
</head>
<body id="welcome_page">

<div class="header"></div>

<div class="topbar">
  <%= link_to "Secretube", welcome_path, class: "home_btn" %>

  <% if logged_in? %>
      <%= link_to current_user.email, dashboard_url, class: "login_btn" %>
  <% else %>
      <%= link_to t("login"), login_path, class: "login_btn" %>
  <% end %>

</div>
<div class="placeholder"></div>

<div class="slogan">
  <h2><%= t(".slogan_h2") %></h2>

  <p><%= t(".slogan_p1") %></p>
  <p><%= t(".slogan_p2") %></p>
  <p><%= t(".slogan_p3") %></p>

  <% if logged_in? %>
      <%= link_to t("my_account"), dashboard_url, class: "register_btn" %>
  <% else %>
      <%= link_to t("create_account"), signup_path, class: "register_btn" %>
  <% end %>

</div>

<div class="demo-show">
  <%= image_tag("welcome/safari.png", class: "demo-safari") %>
  <%= image_tag("welcome/iphone.png", class: "demo-iphone") %>
  <%= image_tag("welcome/ipad.png", class: "demo-ipad") %>
</div>

<div class="bottom-bar">
  <%= fa_icon "language" %>

  <%= select_tag "language", options_for_select(LANGUAGES, I18n.locale.to_s), onchange: 'change_language(this);' %>
</div>
</body>
</html>